services:
  postgres:
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5433"
    image: postgres:12.2-alpine
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ciwallet-bots:
    container_name: ciwallet-bots  
    build:
      context: ..
      args:
        TELEGRAM_CIWALLET_API_TOKEN: ${TELEGRAM_CIWALLET_API_TOKEN}
        TELEGRAM_CIFARM_API_TOKEN: ${TELEGRAM_CIFARM_API_TOKEN}
        TELEGRAM_CIWALLET_MINIAPP_URL: ${TELEGRAM_CIWALLET_MINIAPP_URL}
        TELEGRAM_CIFARM_MINIAPP_URL: ${TELEGRAM_CIFARM_MINIAPP_URL}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
    
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - 9992:9992

volumes:
  data: 