ARG PYTHON_VERSION=3.12.2
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /app

RUN pip install python-telegram-bot
RUN pip install python-dotenv
RUN pip install psycopg2-binary
RUN pip install sqlalchemy
RUN pip install --upgrade sqlalchemy-utils

ARG TELEGRAM_CIWALLET_API_TOKEN
ARG TELEGRAM_CIFARM_API_TOKEN
ARG TELEGRAM_CIWALLET_MINIAPP_URL
ARG TELEGRAM_CIFARM_MINIAPP_URL

ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_HOST
ARG POSTGRES_PORT

# Set environment variables
ENV POSTGRES_USER                    $POSTGRES_USER
ENV POSTGRES_PASSWORD                $POSTGRES_PASSWORD
ENV POSTGRES_DB                      $POSTGRES_DB
ENV POSTGRES_HOST                    $POSTGRES_HOST
ENV POSTGRES_PORT                    $POSTGRES_PORT

ENV TELEGRAM_CIWALLET_API_TOKEN      $TELEGRAM_CIWALLET_API_TOKEN
ENV TELEGRAM_CIFARM_API_TOKEN        $TELEGRAM_CIFARM_API_TOKEN
ENV TELEGRAM_CIWALLET_MINIAPP_URL    $TELEGRAM_CIWALLET_MINIAPP_URL
ENV TELEGRAM_CIFARM_MINIAPP_URL      $TELEGRAM_CIFARM_MINIAPP_URL

RUN 
COPY . .
EXPOSE 9992
CMD python3 src/ciwallet/__main__.py & python3 src/cifarm/__main__.py