version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_POSTGRES_DB: ${POSTGRES_NAKAMA_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  cifarm-server:
    depends_on:
      - postgres
    build: 
      context: ../..
      dockerfile: ./.docker/production/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_NAKAMA_DATABASE: ${POSTGRES_NAKAMA_DATABASE}
    # volumes:
    #   - /home/ubuntu/docker/cifarm-server/data:/nakama/data
    entrypoint: 
      - "/bin/sh"
      - "-ecx"
      - > 
        /nakama/nakama migrate up --database.address ${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAKAMA_DATABASE} &&
        exec /nakama/nakama --config /nakama/data/config.yml --database.address ${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAKAMA_DATABASE}
    expose:
      - "7349" 
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped
volumes:
  data: 